---

-  name: Add sigining-key for B.A.T.M.A.N Advanced apt-repo
   apt_key:
    id: 16EF3F64CB201D9C
    keyserver: pgpkeys.mit.edu

- name: Add B.A.T.M.A.N Advanced apt-repo 
  apt_repository:
    repo: deb https://repo.universe-factory.net/debian/ sid main
    state: present
    filename: 'repo.universe-factory.net'

- name: UGLY HACK! Delete provided batman_adv.ko (we'll use some older version)
  file: 
     path: /lib/modules/3.16.0-4-amd64/kernel/net/batman-adv/batman-adv.ko
     state: absent 

- name: Install B.A.T.M.A.N Advanced Kernel module via dkms
  apt: 
     name:  batman-adv-dkms=2013.4.0* 
     state: present 
     force: yes

- name: Ensure batman-adv is loaded
  modprobe:
     name: batman-adv
     state: present

- name: Install batctl
  apt: 
     name: batctl=2013.4.0* 
     state: present 
     force: yes

- name: Setup batman-Interface 
  template:
    src: roles/gateway/templates/etc/network/interfaces.d/mesh-batman.y2
    dest: /etc/network/interfaces.d/{{ mesh_shortname }}-batman
    owner: root
    group: root
    mode: 0644
  notify: 
    - restart batman
    - restart fastd
  

 
