---

-  name: Add sigining-key for fastd apt-repo
   apt_key:
    id: 16EF3F64CB201D9C
    keyserver: pgpkeys.mit.edu

- name: Add fastd apt-repo
  apt_repository:
    repo: deb https://repo.universe-factory.net/debian/ sid main
    state: present
    filename: 'repo.universe-factory.net'

- name: Install fastd
  apt: 
     name: fastd 
     state: present 

- name: Generate /etc/fastd/fastd.conf
  template:
    src: roles/gateway/templates/etc/fastd/fastd.conf.y2
    dest: /etc/fastd/fastd.conf
    owner: root
    group: root
    mode: 0600


