---

-  name: Add sigining-key for fastd apt-repo
   apt_key:
    id: 16EF3F64CB201D9C
    keyserver: pgpkeys.mit.edu

- name: Add fastd apt-repo
  apt_repository:
    repo: deb https://repo.universe-factory.net/debian/ sid main
    state: present
    filename: 'repo.universe-factory.net'

- name: Install fastd
  apt: 
     name: fastd 
     state: present 

- name: Enable fastd
  service:
    name: fastd
    state: started

- name: Create Directory /etc/fastd/ffnord/
  file:
    path: /etc/fastd/ffnord
    state: directory
    mode: 0600

- name: Generate /etc/fastd/ffnord/fastd.conf
  template:
    src: roles/gateway/templates/etc/fastd/ffnord/fastd.conf.y2
    dest: /etc/fastd/ffnord/fastd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart fastd

- name: Build fastd peers from git
  git:
      repo: https://github.com/Freifunk-Nord/nord-gw-peers
      dest: /etc/fastd/ffnord/peers
  notify:
    - restart fastd
       
  
