---

- name: Install StrongSwan for hide.io
  apt:
    name: strongswan
    state: latest

- name: Install additional modules for StrongSwan
  apt:
    name: libcharon-extra-plugins
    state: latest

- name: Configure StrongSwan for hide.io
  template:
    src: roles/gateway/templates/etc/ipsec.d/hideio.conf.y2
    dest: /etc/ipsec.d/hideio.conf
    owner: root
    group: root
    mode: 0600
-  template:
    src: roles/gateway/templates/etc/ipsec.d/private/hideio.y2
    dest: /etc/ipsec.d/private/hideio
    owner: root
    group: root
    mode: 0600
-  lineinfile:
    dest: /etc/ipsec.conf
    line: 'include /etc/ipsec.d/hideio.conf'
-  lineinfile:
    dest: /etc/ipsec.secrets
    line: 'include /etc/ipsec.d/private/hideio'
  
