---


- name: Install bridge-utils
  apt: 
     name:  bridge-utils 
     state: latest 

- name: Setup Freifunk bridge
  template:
    src:  roles/gateway/templates/etc/network/interfaces.d/mesh-bridge.y2
    dest: /etc/network/interfaces.d/{{ mesh_shortname }}-bridge
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fastd

  

 
